In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from glob import glob
# Aplicar configuraciones de visualización total de Pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

In [3]:
import func_gcp as func_gcp

In [4]:
query_ventas = '''
    select *
    from spsa-operaciones-seg-sd.dst_gestion_operativa.cv_venta
    where codigo_local IN ('V019', 'V094', 'V116')
    and year>= 2025
'''

In [5]:
dff_ventas = func_gcp.read_query(query_ventas)

d:\Usuarios\SP44812227\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\auth\_default.py:113: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
d:\Usuarios\SP44812227\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

In [6]:
dff_ventas.head()

,mes,year,nombre_division,nombre_seccion,nombre_area,nombre_linea,nombre_familia,nombre_tipo_marca,tipo_venta,sub_tipo_Venta,codigo_local,tipo_sss,venta,venta_fa,venta_oh,venta_oh_fa,presupuesto
0,10,2025,ABARROTES,COMESTIBLES ESPECIALES,COMESTIBLES,DESAYUNOS,CEREALES PARA PREPARAR,PROPIOS,Last Mile,Agora Shop,V094,SSS,0.0,0.0,0.0,0.0,3.554524
1,10,2025,ABARROTES,CUIDADO PERSONAL,CUIDADO PERSONAL Y LIMPIEZA,CUIDADO DE LA PIEL,CUIDADO FACIAL,PROPIOS,Last Mile,Agora Shop,V094,SSS,0.0,0.0,0.0,0.0,0.547113
2,7,2025,ABARROTES,LACTEOS,LACTEOS Y CONGELADOS,HUEVOS,HUEVOS,PROPIOS,Last Mile,Agora Shop,V094,SSS,0.0,0.0,0.0,0.0,0.000000
3,3,2025,ABARROTES,CUIDADO PERSONAL,CUIDADO PERSONAL Y LIMPIEZA,PERFUMERIA,ACCESORIOS DE BAÑO,PROPIOS,Venta Ecommerce,Ecommerce,V094,SSS,0.0,0.0,0.0,0.0,0.907227
4,3,2025,ABARROTES,CUIDADO PERSONAL,CUIDADO PERSONAL Y LIMPIEZA,PERFUMERIA,ANTIBACTERIAL,PROPIOS,Venta Ecommerce,Ecommerce,V094,SSS,0.0,0.0,0.0,0.0,1.230652

In [7]:
dff_ventas["sub_tipo_Venta"].unique()

array(['Agora Shop', 'Ecommerce', 'Venta POS', 'Venta CNegocio'],
      dtype=object)

In [8]:
dff_ventas["tipo_venta"].unique()

dff_ventas.groupby(["tipo_venta", "sub_tipo_Venta"]).size()

tipo_venta       sub_tipo_Venta
Last Mile        Agora Shop           92
Venta CNegocio   Venta CNegocio        1
Venta Ecommerce  Ecommerce          1453
Venta POS        Venta POS         24488
dtype: int64

In [9]:
dff_ventas["nombre_linea"].unique()

array(['DESAYUNOS', 'CUIDADO DE LA PIEL', 'HUEVOS', 'PERFUMERIA',
       'CONSERVAS', 'PESCADOS', 'DESINFECTANTES', 'YOGURT', 'VINO',
       'FARMACIA', 'CUIDADO BUCAL', 'CERVEZA', 'CONFITERIA', 'FRUTAS',
       'AGUAS', 'POLLO', 'SIN HUESO', 'MENESTRAS', 'ARROZ',
       'CONDIMENTOS/ADEREZOS', 'PESADOS', 'LIVIANOS',
       'CUIDADO DE LA ROPA', 'LIMPIEZA', 'REPOSTERIA',
       'PANADERIA INDUSTRIAL', 'PAPELERIA LIMPIEZA', 'FONDOS',
       'CUIDADO FAMILIAR', 'BEBIDAS FUNCIONALES', 'LICORES', 'PIQUEOS',
       'ESPUMANTE', 'CUIDADO DEL CABELLO', 'LECHE ENVASADA', 'VARIOS',
       'ACEITES', 'MAQUILLAJE', 'MASCOTAS', 'MENAJE', 'FIDEOS',
       'TEXTIL HOGAR', 'LIMPIADORES / CUIDADO DEL HOGAR', 'LIBRERIA',
       'AUTOMOTOR', 'FERRETERIA', 'BEBIDAS', 'BLANDOS', 'PASTELERIA SECA',
       'ESPECIAL', 'BUFFET', 'ESTACIONALES - AIRE  LIBRE Y DEPORT',
       'ALIMENTOS', 'POSTRES', 'SANGUCHES', 'CHORIZO', 'CIGARROS/HABANOS',
       'JUGOS', 'COLCHONES', 'COMIDAS INSTANTANEAS', 'ALIMENTOS DE BEBES',
       'FETEADOS', 'TROZADO', 'REPOSTERIA Y OTROS', 'MARISCOS',
       'CUIDADO DEL BEBE', 'ACCESORIOS DEL HOGAR', 'DETERGENTE',
       'JUGUETERIA', 'DUROS', 'AZUCAR', 'PAVO', 'ELABORADOS', 'CON HUESO',
       'TORTAS', 'EQUIPOS LIBERADOS', 'ESPECIALIDAD', 'RECARGAS',
       'EMBUTIDOS', 'ENTRADAS', 'GASEOSAS', 'PUERICULTURA', 'HELADOS',
       'HIELO', 'INSUMOS', 'LAVAVAJILLAS', 'MARGARINA Y MANTEQUILLA',
       'BOLSAS COMPOSTABLES', 'OTRAS ESPECIES', 'NIÑOS', 'VESTUARIO BEBA',
       'VESTUARIO NIÑA', 'VESTUARIO BEBO', 'PROCESADOS', 'SEMI-DUROS',
       'TRADICIONAL', 'ROPA INTERIOR  Y MEDIAS', 'ROPA INTERIOR Y MEDIAS',
       'ENTERO', 'VESTUARIO', 'COCINA', 'VESTUARIO JUNIOR F', 'DAMAS',
       'BEBES', 'VESTUARIO JUNIOR', 'VESTUARIO NIÑO', 'MUEBLES',
       'ORGANIZACION DEL HOGAR', 'OTRAS AVES', 'CABALLEROS', 'TARJETA',
       'ACCESORIOS MODA', 'CLIMATIZADORES', 'HOGAR', 'TELEVISORES',
       'CELULARES', 'NAVIDAD', 'CANASTA', 'REFRIGERACION', 'PORTATILES',
       'ACCESORIOS', 'HOME AUDIO'], dtype=object)

In [10]:
dff_ventas["nombre_seccion"].unique()

array(['COMESTIBLES ESPECIALES', 'CUIDADO PERSONAL', 'LACTEOS',
       'PESCADOS', 'LIMPIEZA', 'BEBIDAS CON ALCOHOL', 'FRUTAS',
       'BEBIDAS SIN ALCOHOL', 'AVES', 'VACUNO', 'COMESTIBLES BASICOS',
       'VERDURAS', 'BAZAR', 'PARA LLEVAR', 'VARIOS', 'HOGAR',
       'RESTAURANTS', 'QUESOS', 'PASTELERIA', 'PANADERIA', 'CONGELADOS',
       'CHORIZO', 'TABACO', 'FIAMBRES', 'CERDO', 'MARISCOS', 'TELEFONIA',
       'BEBES', 'INSUMOS', 'BOLSAS COMPOSTABLES', 'OTRAS ESPECIES',
       'CALZADO Y ACCESORIOS', 'NIÑOS', 'DAMAS', 'PEQUEÑOS ELECTRODOM',
       'TARJETA', 'VIDEO', 'CABALLEROS', 'LINEA BLANCA', 'COMPUTO',
       'AUDIO'], dtype=object)

In [12]:
dff_ventas

,mes,year,nombre_division,nombre_seccion,nombre_area,nombre_linea,nombre_familia,nombre_tipo_marca,tipo_venta,sub_tipo_Venta,codigo_local,tipo_sss,venta,venta_fa,venta_oh,venta_oh_fa,presupuesto
0,10,2025,ABARROTES,COMESTIBLES ESPECIALES,COMESTIBLES,DESAYUNOS,CEREALES PARA PREPARAR,PROPIOS,Last Mile,Agora Shop,V094,SSS,0.00,0.00,0.000000,0.00,3.554524
1,10,2025,ABARROTES,CUIDADO PERSONAL,CUIDADO PERSONAL Y LIMPIEZA,CUIDADO DE LA PIEL,CUIDADO FACIAL,PROPIOS,Last Mile,Agora Shop,V094,SSS,0.00,0.00,0.000000,0.00,0.547113
2,7,2025,ABARROTES,LACTEOS,LACTEOS Y CONGELADOS,HUEVOS,HUEVOS,PROPIOS,Last Mile,Agora Shop,V094,SSS,0.00,0.00,0.000000,0.00,0.000000
3,3,2025,ABARROTES,CUIDADO PERSONAL,CUIDADO PERSONAL Y LIMPIEZA,PERFUMERIA,ACCESORIOS DE BAÑO,PROPIOS,Venta Ecommerce,Ecommerce,V094,SSS,0.00,0.00,0.000000,0.00,0.907227
4,3,2025,ABARROTES,CUIDADO PERSONAL,CUIDADO PERSONAL Y LIMPIEZA,PERFUMERIA,ANTIBACTERIAL,PROPIOS,Venta Ecommerce,Ecommerce,V094,SSS,0.00,0.00,0.000000,0.00,1.230652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26029,5,2025,ABARROTES,COMESTIBLES BASICOS,COMESTIBLES,ACEITES,VEGETAL,TERCEROS,Venta POS,Venta POS,V094,SSS,10924.37,10061.43,164.823729,68.87,0.000000
26030,6,2025,ABARROTES,COMESTIBLES ESPECIALES,COMESTIBLES,CONSERVAS,VERDURAS Y LEGUMBRES,TERCEROS,Venta POS,Venta POS,V116,SSS,3851.18,2121.75,51.271971,11.65,0.000000
26031,4,2025,ABARROTES,COMESTIBLES ESPECIALES,COMESTIBLES,CONSERVAS,VERDURAS Y LEGUMBRES,PROPIOS,Venta POS,Venta POS,V116,SSS,873.55,531.83,9.260000,0.00,940.875764
26032,1,2025,ABARROTES,COMESTIBLES ESPECIALES,COMESTIBLES,CONDIMENTOS/ADEREZOS,VINAGRE,PROPIOS,Venta POS,Venta POS,V094,SSS,615.05,793.63,3.220686,0.00,3065.128308
26033,1,2025,ABARROTES,COMESTIBLES ESPECIALES,COMESTIBLES,CONDIMENTOS/ADEREZOS,VINAGRE,TERCEROS,Venta POS,Venta POS,V116,SSS,3106.88,2499.35,48.120000,11.10,0.000000

In [28]:
dff_ventas[dff_ventas["nombre_division"]=="NON FOOD"]

dff_ventas[(dff_ventas["codigo_local"]=="V094")&(dff_ventas["year"]==2025)&(dff_ventas["nombre_division"]=="MISCELANEOS")].groupby(["nombre_division", "nombre_area", "nombre_linea", "nombre_familia"])["venta"].sum()

nombre_division  nombre_area  nombre_linea         nombre_familia
MISCELANEOS      MISCELANEOS  BOLSAS COMPOSTABLES  MASS                   0.00
                                                   PLAZA VEA              0.00
                                                   VIVANDA            88709.45
                              VARIOS               VARIOS            264528.27
Name: venta, dtype: float64

In [22]:
dff_ventas[(dff_ventas["codigo_local"]=="V094")&(dff_ventas["year"]==2025)]["venta"].sum()

np.float64(38359405.04000001)